start: "2025-03-21T17:49:12+08:00"
end: "2025-03-21T18:49:12+08:00"
interval: 10 # 10s

base: node_exporter.yaml

tags:
  - name: hostname
    nullability: 0
    type: STRING
    dist:
      type: weighted_preset
      preset:
        - value: srv-app42
          weight: 1
        - value: host-db18
          weight: 1
        - value: web-proc7
          weight: 1
        - value: compute-53b
          weight: 1
        - value: node21c
          weight: 1
        - value: srv-data09
          weight: 1
        - value: db-worker5
          weight: 1
        - value: vm-prod83
          weight: 1
        - value: host-analytics4
          weight: 1
        - value: worker-batch2
          weight: 1
        - value: compute-vm11
          weight: 1
        - value: app-server16
          weight: 1
        - value: host-backend7
          weight: 1
        - value: node-cache22
          weight: 1
        - value: srv-queue08
          weight: 1
        - value: srv-frontend3
          weight: 1
        - value:  db-shard17
          weight: 1
        - value: vm-staging42
          weight: 1
        - value: compute-web19
          weight: 1
        - value: node-api06
          weight: 1
        - value: srv-backup11
          weight: 1
        - value: host-processing4
          weight: 1
        - value: worker-job15
          weight: 1
        - value: app-gateway8
          weight: 1
        - value: vm-storage24
          weight: 1
  - name: region
    nullability: 0
    type: STRING
    dist:
      type: weighted_preset
      preset:
        - value: ap-southeast-1
          weight: 1
        - value: us-east-1
          weight: 1
        - value: us-west-2
          weight: 1
        - value: eu-central-1
          weight: 1
  - name: az
    nullability: 0
    type: STRING
    dist:
      type: weighted_preset
      preset:
        - value: az-0
          weight: 1
        - value: az-1
          weight: 1
        - value: az-2
          weight: 1
        - value: az-3
          weight: 1
        - value: az-4
          weight: 1
        - value: az-5
          weight: 1
        - value: az-6
          weight: 1
        - value: az-7
          weight: 1

fields:
