name: Black Format Check

on:
  pull_request:
    branches: [ main ]

jobs:
  black-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          python -m pip install black==22.3.0
          
      - name: Check code formatting with Black
        run: |
          python -m black --check .
